apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coturn.fullname" . }}
  labels:
    {{- include "coturn.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "coturn.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "coturn.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "coturn.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if and .Values.password .Values.password.value }}
          {{- if not .Values.password.existingSecret }}
            - name: COTURN_PASSWORD
              value: "{{ .Values.password.value }}"
          {{- end }}
          {{- end }}
          {{- if and .Values.password .Values.password.existingSecret }}
          - name: COTURN_PASSWORD
            valueFrom:
              secretKeyRef: 
                name: {{ .Values.password.existingSecret }}
                key: COTURN_PASSWORD
          {{- end }}
          ports:
            - name: stun-turn-tcp
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: stun-turn-udp
              containerPort: {{ .Values.service.port }}
              protocol: UDP
          args:
            - --listening-port={{ .Values.service.port }}
            - --external-ip={{ .Values.externalIpAddress }}
            - --min-port={{ .Values.minPort | default 49152 }}
            - --max-port={{ .Values.maxPort | default 65535 }}
            - --fingerprint
            - --lt-cred-mech
            - --user=self:$$COTURN_PASSWORD
            - --realm=wiretrustee.com
            - --no-software-attribute
            - --log-file=stdout
            - --no-cli
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
