apiVersion: v1
kind: Service
metadata:
  name: {{ include "coturn.fullname" . }}-stun-turn-udp
  labels:
    {{- include "coturn.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: UDP
      name: stun-turn-udp
  selector:
    {{- include "coturn.selectorLabels" . | nindent 4 }}
