apiVersion: v1
kind: Service
metadata:
  name: {{ include "relay.fullname" . }}-metrics
  labels:
    {{- include "relay.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    {{- include "relay.selectorLabels" . | nindent 4 }}
