{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "management.fullname" . }}-data
  labels:
    {{- include "management.labels" . | nindent 4 }}
spec:
  {{- if .Values.persistence.storageClassName }}
  storageClassName: "{{- .Values.persistence.storageClassName }}"
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.persistence.size | default "1Gi" }}"
{{- end -}}
